services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: my_ecommerce
      POSTGRES_USER : 'postgres'
      POSTGRES_PASSWORD : 'Ecom_S'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5431:5432
    networks:
      - db_connect

  web:
    build: .
    command: >
      sh -c "python manage.py wait_for_db &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    volumes:
      - .:/ecommerce
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - db_connect

volumes:
  postgres_data:

networks:
  db_connect:
    driver: bridge