# Generated by Django 4.1.3 on 2024-08-19 11:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerce", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="slug",
        ),
    ]
