# Generated by Django 4.1.3 on 2024-08-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerce", "0002_remove_product_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="categoryImage",
            field=models.ImageField(upload_to="category -images/"),
        ),
        migrations.AlterField(
            model_name="product",
            name="includes",
            field=models.TextField(default=list),
        ),
    ]
